#!/bin/bash

java -jar \
    -Djava.rmi.server.codebase=http://localhost:6060/compute-client/compute-client-1.0-SNAPSHOT.jar \
    -Djava.security.policy=src/main/resources/client.policy \
    target/compute-client-1.0-SNAPSHOT.jar