#!/bin/bash
# To check if rmiregistry is running enter:
# ps -auxww | grep rmiregistry | egrep -v grep
# It's probably not necessary to set useCodeBaseOnly both for
# rmiregistry and server application?

clear
java -jar \
    -Djava.rmi.server.codebase=http://localhost:6060/compute-api/compute-api-1.0-SNAPSHOT.jar \
    -Djava.rmi.server.hostname=localhost \
    -Djava.security.policy=src/main/resources/server.policy \
    -Djava.rmi.server.useCodebaseOnly=false \
    target/compute-server-1.0-SNAPSHOT.jar

